//Generated by Claude with prompt:
//"For audio output I am considering doing PCM to PDM conversion. How do I implement this in systemverilog?"
//


// =============================================================
// pcm_to_pdm.sv  —  2nd-order delta-sigma PCM → PDM converter
// =============================================================
// Runs entirely on sys_clk; PDM clock is a gated enable signal
// (better FPGA practice than derived clock nets).
//
// Parameters:
//   PCM_WIDTH  : bits of signed PCM input (default 16)
//   CLK_DIV    : sys_clk ticks per PDM clock period.
//                CLK_DIV = round(sys_clk_hz / (fs_hz * OSR))
//                Example: 100 MHz / (48000 * 64) = 32.55 → use 33
//                For exact frequency use an MMCM in a wrapper.
//
// Ports:
//   sys_clk    : main FPGA clock (e.g. 100 MHz from Urbana board)
//   rst_n      : active-low synchronous reset
//   pcm_data   : signed PCM sample, held stable between pcm_valid pulses
//   pcm_valid  : single sys_clk pulse once per audio sample period
//   pdm_out    : 1-bit PDM output (connect to audio codec or RC filter)
//   pdm_clk    : PDM clock signal (use as I2S bit clock or codec MCLK ref)
// =============================================================

module pcm_to_pdm #(
    parameter int PCM_WIDTH = 16,
    parameter int CLK_DIV   = 33       // see note above
) (
    input  logic                         sys_clk,
    input  logic                         rst_n,

    input  logic signed [PCM_WIDTH-1:0]  pcm_data,
    input  logic                         pcm_valid,

    output logic                         pdm_out,
    output logic                         pdm_clk   // buffered PDM clock output
);
    //ChatGPT Fix
    
    
    // ── Guard-bit width for integrators ──────────────────────────────────────
    // 2nd-order modulator: each integrator can grow by ±2×FB per cycle in the
    // worst case.  4 extra bits gives a comfortable headroom margin.
    localparam int ACC_W = PCM_WIDTH + 4;
    
    function automatic signed [ACC_W-1:0] sat(input signed [ACC_W-1:0] x);
        localparam signed [ACC_W-1:0] MAX =  (1 <<< (ACC_W-1)) - 1;
        localparam signed [ACC_W-1:0] MIN = -(1 <<< (ACC_W-1));
        if (x > MAX) return MAX;
        else if (x < MIN) return MIN;
        else return x;
    endfunction
    

    // Feedback magnitude = full-scale of signed PCM input = 2^(PCM_WIDTH-1)
    localparam signed [ACC_W-1:0] FB_POS =  (1 << (PCM_WIDTH - 1)); //CHATGPT -2
    localparam signed [ACC_W-1:0] FB_NEG = -(1 << (PCM_WIDTH - 1));

    // ── PDM clock generation (counter-based, 50 % duty cycle) ────────────────
    logic [$clog2(CLK_DIV)-1:0] clk_cnt;
    logic                        pdm_en;     // one sys_clk-wide enable per PDM edge
    logic                        pdm_clk_r;

    always_ff @(posedge sys_clk) begin
        if (!rst_n) begin
            clk_cnt   <= '0;
            pdm_clk_r <= 1'b0;
            pdm_en    <= 1'b0;
        end else begin
            pdm_en <= 1'b0;                  // default: no enable this cycle
            if (clk_cnt == CLK_DIV - 1) begin
                clk_cnt   <= '0;
                pdm_clk_r <= ~pdm_clk_r;
                pdm_en    <= 1'b1;           // fire enable on rising edge of PDM clk
            end else begin
                clk_cnt <= clk_cnt + 1;
            end
        end
    end

    assign pdm_clk = pdm_clk_r;

    // ── PCM sample hold (zero-order hold between valid pulses) ───────────────
//    logic signed [PCM_WIDTH-1:0] pcm_held;

//    always_ff @(posedge sys_clk) begin
//        if (!rst_n)
//            pcm_held <= '0;
//        else if (pcm_valid)
//            pcm_held <= pcm_data;
//    end
// Use this - only allow a sample update between PDM steps,
// never during one:
    logic signed [PCM_WIDTH-1:0] pcm_held;
    logic signed [PCM_WIDTH-1:0] pcm_staged;  // staging register
    
    // Stage the incoming sample immediately on pcm_valid
    always_ff @(posedge sys_clk) begin
        if (!rst_n)
            pcm_staged <= '0;
        else if (pcm_valid)
            pcm_staged <= pcm_data;
    end

// Only transfer to the held register between PDM steps
// (when pdm_en is NOT firing this cycle)
    always_ff @(posedge sys_clk) begin
        if (!rst_n)
            pcm_held <= '0;
        else if (!pdm_en)
            pcm_held <= pcm_staged;
    end

    // ── 2nd-order cascaded-integrator delta-sigma modulator ──────────────────
    //
    //   Each PDM clock cycle (gated by pdm_en on the rising edge):
    //
    //     fb      = pdm_out ? +FB_POS : FB_NEG
    //     integ1 += pcm_held - fb          �? first integrator
    //     integ2 += integ1   - fb          �? second integrator
    //     pdm_out = (integ2 >= 0) ? 1 : 0  �? 1-bit quantizer
    //
    //   Noise transfer function:  NTF(z) = (1 - z�?�¹)²
    //   Signal transfer function: STF(z) = 1
    //   → quantization noise shaped up to high frequencies, signal passes flat.

    logic signed [ACC_W-1:0] integ1, integ2, integ3;
    logic signed [ACC_W-1:0] fb;
    logic signed [ACC_W-1:0] pcm_ext;   // sign-extended PCM to ACC_W bits

    always_ff @(posedge sys_clk) begin
        if (!rst_n) begin
            integ1  <= '0;
            integ2  <= '0;
            integ3 <= '0;
            pdm_out <= 1'b0;
            fb <= '0;
        end else if (pdm_en) begin
            // Feedback from *previous* cycle's output
            fb      = pdm_out ? FB_POS : FB_NEG;

            // Sign-extend PCM input to accumulator width
            pcm_ext = ACC_W'(signed'(pcm_held));

            // Update integrators
//            integ1  <= integ1 + pcm_ext - fb;
//            integ2  <= integ2 + integ1  - fb;
//                integ1 <= sat(integ1 + pcm_ext - fb); //Chat FIX
                integ1 <= sat(integ1 + pcm_ext - fb); //Chat Fix
//                integ2 <= sat(integ2 + integ1 - fb);
//                integ3 <= sat(integ3 + integ2 - fb);

            // Quantize: MSB is the sign bit — 0 = positive → output 1
            pdm_out <= ~integ1[ACC_W-1];
        end
    end

endmodule


// =============================================================
// Testbench — quick functional check (simulate in Vivado)
// Sweeps a 440 Hz sine wave through the modulator and checks
// that the PDM output density tracks the input amplitude.
// =============================================================

`ifdef SIMULATION
module pcm_to_pdm_tb;
    
    initial begin
        pcm_valid = 0;
        pcm_data  = 0;
    end
    
    localparam int SYS_CLK_HZ  = 100_000_000;
    localparam int AUDIO_FS_HZ =      48_000;
    localparam int OSR         =          64;
    localparam int CLK_DIV     = SYS_CLK_HZ / (AUDIO_FS_HZ * OSR); // = 32

    logic        sys_clk = 0;
    logic        rst_n;
    logic signed [15:0] pcm_data;
    logic        pcm_valid;
    logic        pdm_out;
    logic        pdm_clk;

    pcm_to_pdm #(.PCM_WIDTH(16), .CLK_DIV(CLK_DIV)) dut (.*);

    // 100 MHz clock
    always #5ns sys_clk = ~sys_clk;

    // Audio sample tick: one pulse every 1/48000 s = 20833 ns
    localparam int SAMPLE_TICKS = SYS_CLK_HZ / AUDIO_FS_HZ; // 2083 sys_clk cycles

    int sample_cnt = 0;
    int sample_idx = 0;
    real TWO_PI = 2.0 * 3.14159265;

    always_ff @(posedge sys_clk) begin
        pcm_valid <= 1'b0;
        if (sample_cnt == SAMPLE_TICKS - 1) begin
            sample_cnt <= 0;
            // 440 Hz sine at -6 dBFS
            pcm_data   <= signed'(16'($rtoi(16383.0 *
                              $sin(TWO_PI * 440.0 * sample_idx / AUDIO_FS_HZ))));
            pcm_valid  <= 1'b1;
            sample_idx <= sample_idx + 1;
        end else begin
            sample_cnt <= sample_cnt + 1;
        end
    end

    initial begin
        rst_n = 0;
        repeat(4) @(posedge sys_clk);
        rst_n = 1;
        // Run for 2 ms of simulated audio
        #2_000_000ns;
        $display("Simulation complete");
        $finish;
    end

endmodule
`endif
